// Generated by tailwindcss — do not edit directly
export const TAILWIND_CSS = `
.visible {
  visibility: visible
}

.absolute {
  position: absolute
}

.relative {
  position: relative
}

.inset-0 {
  inset: 0px
}

.-bottom-6 {
  bottom: -1.5rem
}

.-left-1\.5 {
  left: -0.375rem
}

.-left-4 {
  left: -1rem
}

.-left-\[31px\] {
  left: -31px
}

.-right-10 {
  right: -2.5rem
}

.-right-8 {
  right: -2rem
}

.-top-10 {
  top: -2.5rem
}

.-top-8 {
  top: -2rem
}

.bottom-0 {
  bottom: 0px
}

.bottom-2 {
  bottom: 0.5rem
}

.bottom-3 {
  bottom: 0.75rem
}

.bottom-4 {
  bottom: 1rem
}

.bottom-6 {
  bottom: 1.5rem
}

.left-0 {
  left: 0px
}

.left-4 {
  left: 1rem
}

.right-0 {
  right: 0px
}

.right-16 {
  right: 4rem
}

.right-20 {
  right: 5rem
}

.right-24 {
  right: 6rem
}

.right-6 {
  right: 1.5rem
}

.right-8 {
  right: 2rem
}

.top-0 {
  top: 0px
}

.top-1 {
  top: 0.25rem
}

.top-1\/2 {
  top: 50%
}

.top-16 {
  top: 4rem
}

.top-4 {
  top: 1rem
}

.top-6 {
  top: 1.5rem
}

.z-10 {
  z-index: 10
}

.float-left {
  float: left
}

.mx-4 {
  margin-left: 1rem;
  margin-right: 1rem
}

.mx-auto {
  margin-left: auto;
  margin-right: auto
}

.my-2 {
  margin-top: 0.5rem;
  margin-bottom: 0.5rem
}

.mb-1 {
  margin-bottom: 0.25rem
}

.mb-1\.5 {
  margin-bottom: 0.375rem
}

.mb-10 {
  margin-bottom: 2.5rem
}

.mb-12 {
  margin-bottom: 3rem
}

.mb-2 {
  margin-bottom: 0.5rem
}

.mb-3 {
  margin-bottom: 0.75rem
}

.mb-4 {
  margin-bottom: 1rem
}

.mb-5 {
  margin-bottom: 1.25rem
}

.mb-6 {
  margin-bottom: 1.5rem
}

.mb-7 {
  margin-bottom: 1.75rem
}

.mb-8 {
  margin-bottom: 2rem
}

.ml-1 {
  margin-left: 0.25rem
}

.ml-1\.5 {
  margin-left: 0.375rem
}

.ml-2 {
  margin-left: 0.5rem
}

.ml-3 {
  margin-left: 0.75rem
}

.ml-5 {
  margin-left: 1.25rem
}

.ml-auto {
  margin-left: auto
}

.mr-1 {
  margin-right: 0.25rem
}

.mt-0\.5 {
  margin-top: 0.125rem
}

.mt-1 {
  margin-top: 0.25rem
}

.mt-1\.5 {
  margin-top: 0.375rem
}

.mt-2 {
  margin-top: 0.5rem
}

.mt-3 {
  margin-top: 0.75rem
}

.mt-4 {
  margin-top: 1rem
}

.mt-6 {
  margin-top: 1.5rem
}

.mt-8 {
  margin-top: 2rem
}

.block {
  display: block
}

.inline-block {
  display: inline-block
}

.flex {
  display: flex
}

.inline-flex {
  display: inline-flex
}

.table {
  display: table
}

.grid {
  display: grid
}

.h-0 {
  height: 0px
}

.h-0\.5 {
  height: 0.125rem
}

.h-1 {
  height: 0.25rem
}

.h-1\.5 {
  height: 0.375rem
}

.h-12 {
  height: 3rem
}

.h-16 {
  height: 4rem
}

.h-2 {
  height: 0.5rem
}

.h-2\.5 {
  height: 0.625rem
}

.h-20 {
  height: 5rem
}

.h-24 {
  height: 6rem
}

.h-3 {
  height: 0.75rem
}

.h-32 {
  height: 8rem
}

.h-36 {
  height: 9rem
}

.h-4 {
  height: 1rem
}

.h-40 {
  height: 10rem
}

.h-5 {
  height: 1.25rem
}

.h-6 {
  height: 1.5rem
}

.h-8 {
  height: 2rem
}

.h-\[1px\] {
  height: 1px
}

.h-\[2px\] {
  height: 2px
}

.h-\[3px\] {
  height: 3px
}

.h-full {
  height: 100%
}

.h-px {
  height: 1px
}

.w-0 {
  width: 0px
}

.w-1 {
  width: 0.25rem
}

.w-1\.5 {
  width: 0.375rem
}

.w-12 {
  width: 3rem
}

.w-16 {
  width: 4rem
}

.w-2 {
  width: 0.5rem
}

.w-2\.5 {
  width: 0.625rem
}

.w-20 {
  width: 5rem
}

.w-24 {
  width: 6rem
}

.w-28 {
  width: 7rem
}

.w-3 {
  width: 0.75rem
}

.w-32 {
  width: 8rem
}

.w-36 {
  width: 9rem
}

.w-4 {
  width: 1rem
}

.w-40 {
  width: 10rem
}

.w-5 {
  width: 1.25rem
}

.w-6 {
  width: 1.5rem
}

.w-7 {
  width: 1.75rem
}

.w-8 {
  width: 2rem
}

.w-\[32\%\] {
  width: 32%
}

.w-\[35\%\] {
  width: 35%
}

.w-fit {
  width: -moz-fit-content;
  width: fit-content
}

.w-full {
  width: 100%
}

.w-px {
  width: 1px
}

.min-w-0 {
  min-width: 0px
}

.max-w-16 {
  max-width: 4rem
}

.max-w-\[210mm\] {
  max-width: 210mm
}

.flex-1 {
  flex: 1 1 0%
}

.shrink-0 {
  flex-shrink: 0
}

.rotate-45 {
  --tw-rotate: 45deg;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
}

.list-disc {
  list-style-type: disc
}

.list-none {
  list-style-type: none
}

.grid-cols-1 {
  grid-template-columns: repeat(1, minmax(0, 1fr))
}

.grid-cols-2 {
  grid-template-columns: repeat(2, minmax(0, 1fr))
}

.grid-cols-\[140px_1fr\] {
  grid-template-columns: 140px 1fr
}

.flex-wrap {
  flex-wrap: wrap
}

.items-start {
  align-items: flex-start
}

.items-end {
  align-items: flex-end
}

.items-center {
  align-items: center
}

.items-baseline {
  align-items: baseline
}

.justify-center {
  justify-content: center
}

.justify-between {
  justify-content: space-between
}

.gap-1 {
  gap: 0.25rem
}

.gap-1\.5 {
  gap: 0.375rem
}

.gap-2 {
  gap: 0.5rem
}

.gap-2\.5 {
  gap: 0.625rem
}

.gap-3 {
  gap: 0.75rem
}

.gap-4 {
  gap: 1rem
}

.gap-5 {
  gap: 1.25rem
}

.gap-6 {
  gap: 1.5rem
}

.gap-x-1\.5 {
  -moz-column-gap: 0.375rem;
       column-gap: 0.375rem
}

.gap-x-2 {
  -moz-column-gap: 0.5rem;
       column-gap: 0.5rem
}

.gap-x-3 {
  -moz-column-gap: 0.75rem;
       column-gap: 0.75rem
}

.gap-x-4 {
  -moz-column-gap: 1rem;
       column-gap: 1rem
}

.gap-x-6 {
  -moz-column-gap: 1.5rem;
       column-gap: 1.5rem
}

.gap-x-8 {
  -moz-column-gap: 2rem;
       column-gap: 2rem
}

.gap-y-0\.5 {
  row-gap: 0.125rem
}

.gap-y-1 {
  row-gap: 0.25rem
}

.gap-y-1\.5 {
  row-gap: 0.375rem
}

.gap-y-2 {
  row-gap: 0.5rem
}

.gap-y-3 {
  row-gap: 0.75rem
}

.space-y-0\.5 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.125rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.125rem * var(--tw-space-y-reverse))
}

.space-y-1 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.25rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.25rem * var(--tw-space-y-reverse))
}

.space-y-1\.5 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.375rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.375rem * var(--tw-space-y-reverse))
}

.space-y-2 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.5rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.5rem * var(--tw-space-y-reverse))
}

.space-y-2\.5 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.625rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.625rem * var(--tw-space-y-reverse))
}

.space-y-3 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.75rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.75rem * var(--tw-space-y-reverse))
}

.space-y-4 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(1rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(1rem * var(--tw-space-y-reverse))
}

.space-y-5 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(1.25rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(1.25rem * var(--tw-space-y-reverse))
}

.space-y-6 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(1.5rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(1.5rem * var(--tw-space-y-reverse))
}

.overflow-hidden {
  overflow: hidden
}

.break-all {
  word-break: break-all
}

.rounded {
  border-radius: 0.25rem
}

.rounded-2xl {
  border-radius: 1rem
}

.rounded-full {
  border-radius: 9999px
}

.rounded-lg {
  border-radius: 0.5rem
}

.rounded-md {
  border-radius: 0.375rem
}

.rounded-sm {
  border-radius: 0.125rem
}

.rounded-xl {
  border-radius: 0.75rem
}

.rounded-l-lg {
  border-top-left-radius: 0.5rem;
  border-bottom-left-radius: 0.5rem
}

.rounded-r-md {
  border-top-right-radius: 0.375rem;
  border-bottom-right-radius: 0.375rem
}

.border {
  border-width: 1px
}

.border-2 {
  border-width: 2px
}

.border-4 {
  border-width: 4px
}

.border-b {
  border-bottom-width: 1px
}

.border-b-2 {
  border-bottom-width: 2px
}

.border-b-4 {
  border-bottom-width: 4px
}

.border-l-2 {
  border-left-width: 2px
}

.border-l-4 {
  border-left-width: 4px
}

.border-l-\[3px\] {
  border-left-width: 3px
}

.border-r {
  border-right-width: 1px
}

.border-t {
  border-top-width: 1px
}

.border-black {
  --tw-border-opacity: 1;
  border-color: rgb(0 0 0 / var(--tw-border-opacity, 1))
}

.border-white {
  --tw-border-opacity: 1;
  border-color: rgb(255 255 255 / var(--tw-border-opacity, 1))
}

.border-white\/10 {
  border-color: rgb(255 255 255 / 0.1)
}

.border-white\/20 {
  border-color: rgb(255 255 255 / 0.2)
}

.border-white\/40 {
  border-color: rgb(255 255 255 / 0.4)
}

.border-zinc-100 {
  --tw-border-opacity: 1;
  border-color: rgb(244 244 245 / var(--tw-border-opacity, 1))
}

.border-zinc-200 {
  --tw-border-opacity: 1;
  border-color: rgb(228 228 231 / var(--tw-border-opacity, 1))
}

.border-zinc-300 {
  --tw-border-opacity: 1;
  border-color: rgb(212 212 216 / var(--tw-border-opacity, 1))
}

.border-zinc-800 {
  --tw-border-opacity: 1;
  border-color: rgb(39 39 42 / var(--tw-border-opacity, 1))
}

.bg-\[\#27c93f\] {
  --tw-bg-opacity: 1;
  background-color: rgb(39 201 63 / var(--tw-bg-opacity, 1))
}

.bg-\[\#ff5f56\] {
  --tw-bg-opacity: 1;
  background-color: rgb(255 95 86 / var(--tw-bg-opacity, 1))
}

.bg-\[\#ffbd2e\] {
  --tw-bg-opacity: 1;
  background-color: rgb(255 189 46 / var(--tw-bg-opacity, 1))
}

.bg-black {
  --tw-bg-opacity: 1;
  background-color: rgb(0 0 0 / var(--tw-bg-opacity, 1))
}

.bg-red-50 {
  --tw-bg-opacity: 1;
  background-color: rgb(254 242 242 / var(--tw-bg-opacity, 1))
}

.bg-white {
  --tw-bg-opacity: 1;
  background-color: rgb(255 255 255 / var(--tw-bg-opacity, 1))
}

.bg-white\/10 {
  background-color: rgb(255 255 255 / 0.1)
}

.bg-white\/15 {
  background-color: rgb(255 255 255 / 0.15)
}

.bg-white\/20 {
  background-color: rgb(255 255 255 / 0.2)
}

.bg-white\/5 {
  background-color: rgb(255 255 255 / 0.05)
}

.bg-zinc-100 {
  --tw-bg-opacity: 1;
  background-color: rgb(244 244 245 / var(--tw-bg-opacity, 1))
}

.bg-zinc-200 {
  --tw-bg-opacity: 1;
  background-color: rgb(228 228 231 / var(--tw-bg-opacity, 1))
}

.bg-zinc-50 {
  --tw-bg-opacity: 1;
  background-color: rgb(250 250 250 / var(--tw-bg-opacity, 1))
}

.p-0\.5 {
  padding: 0.125rem
}

.p-1 {
  padding: 0.25rem
}

.p-2\.5 {
  padding: 0.625rem
}

.p-3 {
  padding: 0.75rem
}

.p-4 {
  padding: 1rem
}

.p-5 {
  padding: 1.25rem
}

.p-6 {
  padding: 1.5rem
}

.p-8 {
  padding: 2rem
}

.p-\[2px\] {
  padding: 2px
}

.p-\[3px\] {
  padding: 3px
}

.px-1\.5 {
  padding-left: 0.375rem;
  padding-right: 0.375rem
}

.px-10 {
  padding-left: 2.5rem;
  padding-right: 2.5rem
}

.px-2 {
  padding-left: 0.5rem;
  padding-right: 0.5rem
}

.px-2\.5 {
  padding-left: 0.625rem;
  padding-right: 0.625rem
}

.px-3 {
  padding-left: 0.75rem;
  padding-right: 0.75rem
}

.px-4 {
  padding-left: 1rem;
  padding-right: 1rem
}

.px-6 {
  padding-left: 1.5rem;
  padding-right: 1.5rem
}

.px-8 {
  padding-left: 2rem;
  padding-right: 2rem
}

.py-0\.5 {
  padding-top: 0.125rem;
  padding-bottom: 0.125rem
}

.py-1 {
  padding-top: 0.25rem;
  padding-bottom: 0.25rem
}

.py-1\.5 {
  padding-top: 0.375rem;
  padding-bottom: 0.375rem
}

.py-10 {
  padding-top: 2.5rem;
  padding-bottom: 2.5rem
}

.py-2 {
  padding-top: 0.5rem;
  padding-bottom: 0.5rem
}

.py-3 {
  padding-top: 0.75rem;
  padding-bottom: 0.75rem
}

.py-4 {
  padding-top: 1rem;
  padding-bottom: 1rem
}

.py-5 {
  padding-top: 1.25rem;
  padding-bottom: 1.25rem
}

.py-6 {
  padding-top: 1.5rem;
  padding-bottom: 1.5rem
}

.py-8 {
  padding-top: 2rem;
  padding-bottom: 2rem
}

.py-px {
  padding-top: 1px;
  padding-bottom: 1px
}

.pb-0\.5 {
  padding-bottom: 0.125rem
}

.pb-1 {
  padding-bottom: 0.25rem
}

.pb-1\.5 {
  padding-bottom: 0.375rem
}

.pb-2 {
  padding-bottom: 0.5rem
}

.pb-4 {
  padding-bottom: 1rem
}

.pb-5 {
  padding-bottom: 1.25rem
}

.pb-6 {
  padding-bottom: 1.5rem
}

.pl-3 {
  padding-left: 0.75rem
}

.pl-3\.5 {
  padding-left: 0.875rem
}

.pl-4 {
  padding-left: 1rem
}

.pl-5 {
  padding-left: 1.25rem
}

.pl-6 {
  padding-left: 1.5rem
}

.pt-0\.5 {
  padding-top: 0.125rem
}

.pt-3 {
  padding-top: 0.75rem
}

.pt-4 {
  padding-top: 1rem
}

.pt-6 {
  padding-top: 1.5rem
}

.text-left {
  text-align: left
}

.text-center {
  text-align: center
}

.text-right {
  text-align: right
}

.indent-8 {
  text-indent: 2rem
}

.text-2xl {
  font-size: 1.5rem;
  line-height: 2rem
}

.text-3xl {
  font-size: 1.875rem;
  line-height: 2.25rem
}

.text-4xl {
  font-size: 2.25rem;
  line-height: 2.5rem
}

.text-\[10px\] {
  font-size: 10px
}

.text-\[11px\] {
  font-size: 11px
}

.text-\[13px\] {
  font-size: 13px
}

.text-\[9px\] {
  font-size: 9px
}

.text-base {
  font-size: 1rem;
  line-height: 1.5rem
}

.text-lg {
  font-size: 1.125rem;
  line-height: 1.75rem
}

.text-sm {
  font-size: 0.875rem;
  line-height: 1.25rem
}

.text-xl {
  font-size: 1.25rem;
  line-height: 1.75rem
}

.text-xs {
  font-size: 0.75rem;
  line-height: 1rem
}

.font-black {
  font-weight: 900
}

.font-bold {
  font-weight: 700
}

.font-extrabold {
  font-weight: 800
}

.font-light {
  font-weight: 300
}

.font-medium {
  font-weight: 500
}

.font-normal {
  font-weight: 400
}

.font-semibold {
  font-weight: 600
}

.uppercase {
  text-transform: uppercase
}

.italic {
  font-style: italic
}

.leading-loose {
  line-height: 2
}

.leading-none {
  line-height: 1
}

.leading-relaxed {
  line-height: 1.625
}

.tracking-\[0\.15em\] {
  letter-spacing: 0.15em
}

.tracking-\[0\.25em\] {
  letter-spacing: 0.25em
}

.tracking-\[0\.2em\] {
  letter-spacing: 0.2em
}

.tracking-\[0\.3em\] {
  letter-spacing: 0.3em
}

.tracking-tight {
  letter-spacing: -0.025em
}

.tracking-wide {
  letter-spacing: 0.025em
}

.tracking-wider {
  letter-spacing: 0.05em
}

.tracking-widest {
  letter-spacing: 0.1em
}

.text-black {
  --tw-text-opacity: 1;
  color: rgb(0 0 0 / var(--tw-text-opacity, 1))
}

.text-blue-100 {
  --tw-text-opacity: 1;
  color: rgb(219 234 254 / var(--tw-text-opacity, 1))
}

.text-blue-200 {
  --tw-text-opacity: 1;
  color: rgb(191 219 254 / var(--tw-text-opacity, 1))
}

.text-blue-300 {
  --tw-text-opacity: 1;
  color: rgb(147 197 253 / var(--tw-text-opacity, 1))
}

.text-gray-400 {
  --tw-text-opacity: 1;
  color: rgb(156 163 175 / var(--tw-text-opacity, 1))
}

.text-gray-500 {
  --tw-text-opacity: 1;
  color: rgb(107 114 128 / var(--tw-text-opacity, 1))
}

.text-gray-600 {
  --tw-text-opacity: 1;
  color: rgb(75 85 99 / var(--tw-text-opacity, 1))
}

.text-red-100 {
  --tw-text-opacity: 1;
  color: rgb(254 226 226 / var(--tw-text-opacity, 1))
}

.text-red-100\/80 {
  color: rgb(254 226 226 / 0.8)
}

.text-slate-400 {
  --tw-text-opacity: 1;
  color: rgb(148 163 184 / var(--tw-text-opacity, 1))
}

.text-slate-500 {
  --tw-text-opacity: 1;
  color: rgb(100 116 139 / var(--tw-text-opacity, 1))
}

.text-slate-600 {
  --tw-text-opacity: 1;
  color: rgb(71 85 105 / var(--tw-text-opacity, 1))
}

.text-white {
  --tw-text-opacity: 1;
  color: rgb(255 255 255 / var(--tw-text-opacity, 1))
}

.text-white\/30 {
  color: rgb(255 255 255 / 0.3)
}

.text-white\/60 {
  color: rgb(255 255 255 / 0.6)
}

.text-white\/70 {
  color: rgb(255 255 255 / 0.7)
}

.text-white\/80 {
  color: rgb(255 255 255 / 0.8)
}

.text-zinc-200 {
  --tw-text-opacity: 1;
  color: rgb(228 228 231 / var(--tw-text-opacity, 1))
}

.text-zinc-300 {
  --tw-text-opacity: 1;
  color: rgb(212 212 216 / var(--tw-text-opacity, 1))
}

.text-zinc-400 {
  --tw-text-opacity: 1;
  color: rgb(161 161 170 / var(--tw-text-opacity, 1))
}

.text-zinc-500 {
  --tw-text-opacity: 1;
  color: rgb(113 113 122 / var(--tw-text-opacity, 1))
}

.text-zinc-600 {
  --tw-text-opacity: 1;
  color: rgb(82 82 91 / var(--tw-text-opacity, 1))
}

.text-zinc-700 {
  --tw-text-opacity: 1;
  color: rgb(63 63 70 / var(--tw-text-opacity, 1))
}

.text-zinc-800 {
  --tw-text-opacity: 1;
  color: rgb(39 39 42 / var(--tw-text-opacity, 1))
}

.text-zinc-900 {
  --tw-text-opacity: 1;
  color: rgb(24 24 27 / var(--tw-text-opacity, 1))
}

.opacity-10 {
  opacity: 0.1
}

.opacity-20 {
  opacity: 0.2
}

.opacity-30 {
  opacity: 0.3
}

.shadow-lg {
  --tw-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  --tw-shadow-colored: 0 10px 15px -3px var(--tw-shadow-color), 0 4px 6px -4px var(--tw-shadow-color);
  box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)
}

.shadow-sm {
  --tw-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);
  --tw-shadow-colored: 0 1px 2px 0 var(--tw-shadow-color);
  box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)
}

.shadow-xl {
  --tw-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);
  --tw-shadow-colored: 0 20px 25px -5px var(--tw-shadow-color), 0 8px 10px -6px var(--tw-shadow-color);
  box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)
}

.filter {
  filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)
}

.transition-colors {
  transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 150ms
}

.hover\:bg-zinc-50\/50:hover {
  background-color: rgb(250 250 250 / 0.5)
}

@media (min-width: 640px) {
  .sm\:grid-cols-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr))
  }
}
`;
